// MMS Gardening Services — nursery restored and mobile-safe
const products=[
{name:'Yellow Pond Iris',category:'Bulbs & Rhizomes',price:'£5.00 per pot',images:['https://www.rootsplants.co.uk/cdn/shop/files/30_bae03265-3630-4e58-b748-aeec2df0f9da.jpg?v=1721169322'],desc:'A striking, hardy water-loving perennial with bright yellow flowers. Ideal for pond margins and reliably moist areas.',details:'Full sun or partial shade · Moist to wet soil · Hardy in the UK · Flowers in late spring and summer'},
{name:'Orange Day Lily',category:'Bulbs & Rhizomes',price:'£3.00 per pot',images:['https://sprouthome.com/cdn/shop/products/HemerCH1_sprout.jpg?v=1743283625&width=1733'],desc:'A bright and cheerful perennial producing warm orange trumpet-shaped flowers above strap-like foliage.',details:'Sun or partial shade · Well-drained soil · Hardy perennial · Summer flowering'},
{name:'Purple Iris',category:'Bulbs & Rhizomes',price:'£5.00 per pot',images:['https://groffsplantfarm.com/inventory/thumbnail.php?num=0&plu=3614&v=c2eb804'],desc:'A beautiful hardy iris with elegant purple flowers and sword-shaped foliage.',details:'Full sun or partial shade · Moist but well-drained soil · Hardy perennial'},
{name:'Crocosmia Lucifer',category:'Bulbs & Rhizomes',price:'£5.00 per pot',images:['https://saintamourcreation.com/cdn/shop/files/crocosmialucifer_1.jpg?v=1753371514&width=480'],desc:'A dramatic summer perennial with vivid red flowers, bringing strong colour to garden borders.',details:'Full sun or partial shade · Fertile, well-drained soil · Summer flowering'}];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logImage='https://www.certainlywood.co.uk/cdn/shop/files/one-Wood-net.jpg?v=1752262134&width=900';
const roseImage='https://commons.wikimedia.org/wiki/Special:Redirect/file/Rose_garden_flower.jpg';
const hydrangeaImage='https://commons.wikimedia.org/wiki/Special:Redirect/file/Hydrangea_macrophylla_Blueming.jpg';
const bulbsImage='https://www.rootsplants.co.uk/cdn/shop/files/30_bae03265-3630-4e58-b748-aeec2df0f9da.jpg?v=1721169322';
function getItems(){return document.getElementById('items')}
function renderCategories(){const items=getItems();if(!items)return;items.innerHTML=`<div class="nursery-category-grid"><article class="nursery-category"><div class="service-photo" style="background-image:url('${bulbsImage}');background-size:cover;background-position:center"></div><h3>Bulbs & Rhizomes</h3><p>Browse bulbs and rhizomatous plants currently available from MMS Nursery.</p><button class="btn" type="button" onclick="showProducts()">View plants</button></article><article class="nursery-category"><div class="service-photo" style="background-image:url('${roseImage}');background-size:cover;background-position:center"></div><h3>Roses</h3><p>Garden roses in a range of colours and varieties. Stock will be added as available.</p><span class="nursery-status">Stock being added</span></article><article class="nursery-category"><div class="service-photo" style="background-image:url('${hydrangeaImage}');background-size:cover;background-position:center"></div><h3>Hydrangeas</h3><p>Beautiful hydrangeas for borders, beds and containers. Stock will be added as available.</p><span class="nursery-status">Stock being added</span></article><article class="nursery-card logs-card" role="button" tabindex="0" onclick="showLogs()"><img src="${logImage}" alt="Netted firewood logs"><div><h3>Netted Logs</h3><p>Dry stored for two years.</p><strong>From £5</strong></div></article><article class="nursery-clearance-card"><div class="clearance-badge">CLEARANCE</div><h3>Nursery Clearance</h3><p>Great-value plants and garden stock reduced to clear.</p></article></div>`}
function showLogs(){const items=getItems();if(!items)return;items.innerHTML=`<div class="nursery-back"><button class="btn" type="button" onclick="renderCategories()">← Back to nursery</button></div><article class="nursery-product logs-detail"><div class="nursery-images"><img src="${logImage}" alt="Netted firewood logs"></div><div class="nursery-product-copy"><small>NURSERY · FIREWOOD</small><h3>Netted Logs — Dry stored for two years</h3><p>Quality firewood, dry stored for two years before sale.</p><div class="log-options"><button class="btn" type="button" onclick="buyLogs('Small bag','£5')">Small bag — £5</button><button class="btn" type="button" onclick="buyLogs('Large bag','£7')">Large bag — £7</button></div></div></article>`}
function buyLogs(size,price){const text=encodeURIComponent(`Hi MMS Gardening Services, I'd like to enquire about ${size} of netted logs at ${price}.`);window.open(`https://wa.me/447989892662?text=${text}`,'_blank')}
function showProducts(){const items=getItems();if(!items)return;items.innerHTML=`<div class="nursery-back"><button class="btn" type="button" onclick="renderCategories()">← Back to nursery</button></div><div class="nursery-product-list">${products.map((p,i)=>`<article class="nursery-list-card"><div class="nursery-list-image"><img src="${p.images[0]}" alt="${esc(p.name)} in a nursery pot"></div><div><small>${p.category}</small><h3>${p.name}</h3><div class="nursery-price">${p.price}</div><p>${p.desc}</p><button class="btn" type="button" onclick="showProduct(${i})">View ${esc(p.name)}</button></div></article>`).join('')}</div>`}
function showProduct(i){const items=getItems();if(!items)return;const p=products[i];items.innerHTML=`<div class="nursery-back"><button class="btn" type="button" onclick="showProducts()">← Back to Bulbs & Rhizomes</button></div><article class="nursery-product"><div class="nursery-images">${p.images.map(src=>`<img src="${src}" alt="${esc(p.name)} in a nursery pot in flower" loading="eager">`).join('')}</div><div class="nursery-product-copy"><small>${p.category.toUpperCase()}</small><h3>${p.name}</h3><div class="nursery-price">${p.price}</div><p>${p.desc}</p><p><strong>Growing guide:</strong> ${p.details}</p><button class="btn" type="button" onclick="addToBasket(${i})">Add to basket</button> <button class="btn light" type="button" onclick="buyNow(${i})">Buy now</button></div></article>`)}
function addToBasket(i){let basket=JSON.parse(localStorage.getItem('mmsBasket')||'[]');basket.push({name:products[i].name,price:products[i].price});localStorage.setItem('mmsBasket',JSON.stringify(basket));alert(`${products[i].name} added to your basket.`)}
function buyNow(i){const p=products[i];const text=encodeURIComponent(`Hi MMS Gardening Services, I'd like to buy ${p.name} at ${p.price}. Please let me know how to arrange collection/delivery.`);window.open(`https://wa.me/447989892662?text=${text}`,'_blank')}

const maintenancePhotos=[
{title:'Mowing',desc:'Regular lawn mowing and keeping grass looking neat.',src:'https://images.pexels.com/photos/6728930/pexels-photo-6728930.jpeg',alt:'Gardener mowing a lawn'},
{title:'Strimming & Edging',desc:'Strimming grass and keeping lawn and borders neatly defined.',src:'https://images.pexels.com/photos/6363742/pexels-photo-6363742.jpeg',alt:'Gardener using a grass trimmer'},
{title:'Weeding',desc:'Keeping beds and borders clear and cared for.',src:'https://images.pexels.com/photos/5027619/pexels-photo-5027619.jpeg',alt:'Gardener weeding and trimming plants'},
{title:'Pruning',desc:'Pruning shrubs and growth to keep the garden tidy.',src:'https://images.pexels.com/photos/34437457/pexels-photo-34437457.jpeg',alt:'Gardener pruning a hedge'},
{title:'General Garden Upkeep',desc:'Hands-on care to keep the whole garden looking presentable.',src:'https://images.pexels.com/photos/12328926/pexels-photo-12328926.jpeg',alt:'Gardener caring for plants'}
];
function addMaintenanceGallery(){
 const services=document.getElementById('services');
 if(!services||document.getElementById('garden-maintenance-gallery'))return;
 const style=document.createElement('style');style.textContent='#garden-maintenance-gallery .maintenance-single-list{display:flex;flex-direction:column;gap:1.5rem;max-width:760px;margin:2rem auto}#garden-maintenance-gallery .maintenance-photo-card{display:flex;flex-direction:column;background:#fff;border:1px solid #d9e6d4;border-radius:18px;overflow:hidden;box-shadow:0 8px 24px rgba(0,0,0,.06)}#garden-maintenance-gallery .maintenance-photo-card img{display:block;width:100%;height:auto;aspect-ratio:4/5;object-fit:cover}#garden-maintenance-gallery .maintenance-photo-card>div{padding:1.25rem 1.4rem}';document.head.appendChild(style);
 const section=document.createElement('section');section.id='garden-maintenance-gallery';section.className='hedge-domestic';
 section.innerHTML=`<small>GARDEN MAINTENANCE</small><h2>Garden Maintenance — Our Work</h2><p class="intro">One portrait photograph for each type of maintenance work, so customers can simply scroll down through the jobs.</p><div class="maintenance-single-list">${maintenancePhotos.map(p=>`<article class="maintenance-photo-card"><img src="${p.src}" alt="${esc(p.alt)}" loading="lazy"><div><small>MMS GARDEN MAINTENANCE</small><h3>${esc(p.title)}</h3><p>${esc(p.desc)}</p></div></article>`).join('')}</div><a class="btn" href="#contact" data-quote="maintenance">Request a garden maintenance quote</a>`;
 services.insertAdjacentElement('afterend',section);
}
function initNursery(){const menu=document.getElementById('menu');if(menu)menu.onclick=()=>document.querySelector('.links').classList.toggle('open');document.querySelectorAll('.links a').forEach(a=>a.onclick=()=>document.querySelector('.links').classList.remove('open'));const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();renderCategories();addMaintenanceGallery()}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initNursery)}else{initNursery()}
