// MMS nursery and site interactions
const products=[{name:'Yellow Pond Iris',category:'Bulbs & Rhizomes',price:'£5.00 per pot',images:['images/yellow-pond-iris-1.jpg','images/yellow-pond-iris-2.jpg'],desc:'A striking, hardy water-loving perennial with sword-like grey-green leaves and bright yellow flowers. Ideal for pond margins and reliably moist areas.',details:'Full sun or partial shade · Moist to wet soil · Hardy in the UK · Flowers in late spring and summer'},{name:'Orange Day Lily',category:'Bulbs & Rhizomes',price:'£3.00 per pot',images:['images/orange-day-lily-1.jpg','images/orange-day-lily-2.jpg'],desc:'A bright and cheerful perennial producing warm orange trumpet-shaped flowers above strap-like foliage.',details:'Sun or partial shade · Well-drained soil · Hardy perennial · Summer flowering'},{name:'Purple Iris',category:'Bulbs & Rhizomes',price:'£5.00 per pot',images:['images/purple-iris.jpg'],desc:'A beautiful hardy iris with elegant purple flowers and sword-shaped foliage.',details:'Full sun or partial shade · Moist but well-drained soil · Hardy perennial'},{name:'Crocosmia Lucifer',category:'Bulbs & Rhizomes',price:'£5.00 per pot',images:['images/crocosmia-lucifer.jpg'],desc:'A dramatic summer perennial with vivid red flowers, bringing strong colour to garden borders.',details:'Full sun or partial shade · Fertile, well-drained soil · Summer flowering'}];
const items=document.getElementById('items');
const esc=s=>String(s).replace(/[&<>\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]));
const logImage='https://www.certainlywood.co.uk/cdn/shop/files/one-Wood-net.jpg?v=1752262134&width=900';
const nurseryCards=[{name:'Roses',text:'Garden roses in a range of colours and varieties. Stock will be added as available.'},{name:'Shrubs',text:'A selection of garden shrubs for borders, beds and containers. Stock will be added as available.'},{name:'Hedging Plants',text:'Hedging plants for new boundaries, replacements and larger planting jobs. Trade enquiries welcome.'}];
function renderCategories(){items.innerHTML=`<div class="nursery-category-grid"><article class="nursery-category"><div class="service-photo photo-aquatics"></div><h3>Bulbs & Rhizomes</h3><p>Browse bulbs and rhizomatous plants currently available from MMS Nursery.</p><button class="btn" type="button" onclick="showProducts()">View plants</button></article>${nurseryCards.map(c=>`<article class="nursery-category nursery-simple-card"><div class="nursery-card-icon">🌱</div><h3>${c.name}</h3><p>${c.text}</p><span class="nursery-status">Stock being added</span></article>`).join('')}<article class="nursery-card logs-card" role="button" tabindex="0" onclick="showLogs()" onkeydown="if(event.key==='Enter'||event.key===' ')showLogs()"><img src="${logImage}" alt="Netted firewood logs in a mesh bag"><div><h3>Netted Logs</h3><p>Dry stored for two years.</p><strong>From £5</strong><span class="logs-click"> Click to view sizes</span></div></article><article class="nursery-clearance-card"><div class="clearance-badge">CLEARANCE</div><h3>Nursery Clearance</h3><p>Great-value plants and garden stock reduced to clear. Check back regularly for bargains.</p><strong>Clearance prices while stocks last</strong></article></div>`}
function showLogs(){items.innerHTML=`<div class="nursery-back"><button class="btn" type="button" onclick="renderCategories()">← Back to nursery</button></div><article class="nursery-product logs-detail"><div class="nursery-images"><img src="${logImage}" alt="Netted firewood logs in a mesh bag"></div><div class="nursery-product-copy"><small>NURSERY · FIREWOOD</small><h3>Netted Logs — Dry stored for two years</h3><p>Quality firewood, dry stored for two years before sale. Choose the bag size that suits you.</p><div class="log-options"><button class="btn" type="button" onclick="buyLogs('Small bag','£5')">Small bag — £5</button><button class="btn" type="button" onclick="buyLogs('Large bag','£7')">Large bag — £7</button></div><p><strong>Local delivery available on bulk orders.</strong> Message MMS to discuss your requirements and delivery.</p><button class="btn light" type="button" onclick="buyLogs('Bulk order','local delivery')">Enquire about bulk delivery</button></div></article>`}
function buyLogs(size,price){const text=encodeURIComponent(`Hi MMS Gardening Services, I'd like to enquire about ${size} of netted logs${price.startsWith('£')?` at ${price}`:''}. Please let me know about availability${price==='local delivery'?' and local delivery on a bulk order':''}.`);window.open(`https://wa.me/447989892662?text=${text}`,'_blank')}
function showProducts(){items.innerHTML=`<div class="nursery-back"><button class="btn" type="button" onclick="renderCategories()">← Back to nursery</button></div><div class="nursery-product-list">${products.map((p,i)=>`<article class="nursery-list-card"><div class="nursery-list-image"><img src="${p.images[0]}" alt="${esc(p.name)}"></div><div><small>${p.category}</small><h3>${p.name}</h3><div class="nursery-price">${p.price}</div><p>${p.desc}</p><button class="btn" type="button" onclick="showProduct(${i})">View ${esc(p.name)}</button></div></article>`).join('')}</div>`}
function showProduct(i){const p=products[i];items.innerHTML=`<div class="nursery-back"><button class="btn" type="button" onclick="showProducts()">← Back to Bulbs & Rhizomes</button></div><article class="nursery-product"><div class="nursery-images">${p.images.map((src,n)=>`<img src="${src}" alt="${esc(p.name)}${n?' in flower':''}">`).join('')}</div><div class="nursery-product-copy"><small>${p.category.toUpperCase()}</small><h3>${p.name}</h3><div class="nursery-price">${p.price}</div><p>${p.desc}</p><p><strong>Growing guide:</strong> ${p.details}</p><p class="photo-note">The photographs are MMS nursery photographs where supplied, so customers can see the plants they are buying.</p><button class="btn" type="button" onclick="addToBasket(${i})">Add to basket</button> <button class="btn light" type="button" onclick="buyNow(${i})">Buy now</button></div></article>`}
function addToBasket(i){let basket=JSON.parse(localStorage.getItem('mmsBasket')||'[]');basket.push({name:products[i].name,price:products[i].price});localStorage.setItem('mmsBasket',JSON.stringify(basket));alert(`${products[i].name} added to your basket.`)}
function buyNow(i){const p=products[i];const text=encodeURIComponent(`Hi MMS Gardening Services, I'd like to buy ${p.name} at ${p.price}. Please let me know how to arrange collection/delivery.`);window.open(`https://wa.me/447989892662?text=${text}`,'_blank')}
const menu=document.getElementById('menu');if(menu)menu.onclick=()=>document.querySelector('.links').classList.toggle('open');document.querySelectorAll('.links a').forEach(a=>a.onclick=()=>document.querySelector('.links').classList.remove('open'));const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const about=document.querySelector('#about');if(about){const photo=about.querySelector('.photo');const heading=about.querySelector('h2');if(photo){photo.style.display='none';}if(heading)heading.textContent='A local team you can rely on';const first=about.querySelector('p');if(first)first.textContent="At MMS Gardening Services, we're a friendly, hardworking team dedicated to keeping gardens and outdoor spaces looking their best all year round.";const second=about.querySelectorAll('p')[1];if(second)second.textContent="From regular maintenance to one-off projects, we work together with pride and care to deliver a service you can trust.";}
const nurseryStyle=document.createElement('style');nurseryStyle.textContent=`.nursery-category-grid{grid-column:1/-1;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.nursery-category-grid article{margin:0}.nursery-simple-card{min-height:210px}.nursery-card.logs-card{grid-column:auto;display:flex;align-items:center;gap:16px;padding:14px 16px;min-height:130px;cursor:pointer}.logs-card img{width:105px;height:90px;object-fit:cover;border-radius:12px}.logs-card h3{margin:0 0 6px}.logs-card p{margin:0 0 6px}.logs-click{display:block;font-size:13px;font-weight:700;letter-spacing:.04em;margin-top:4px}.nursery-card-icon{font-size:36px;margin-bottom:10px}.nursery-status{font-size:14px;font-weight:700;letter-spacing:.06em;color:#66856f}.nursery-clearance-card{padding:22px;border-radius:20px;border:2px dashed #a36b3b;background:#fff8ed;display:flex;flex-direction:column;justify-content:center}.clearance-badge{display:inline-block;width:max-content;padding:5px 10px;border-radius:999px;background:#a36b3b;color:white;font-size:12px;font-weight:800;letter-spacing:.12em;margin-bottom:10px}.nursery-clearance-card h3{margin:0 0 8px}.nursery-clearance-card p{margin:0 0 10px}.logs-detail .nursery-images img{width:100%;max-height:420px;object-fit:cover;border-radius:18px}.log-options{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0}.logs-detail .nursery-product-copy h3{font-size:clamp(28px,4vw,42px)}@media(max-width:600px){.nursery-category-grid{grid-template-columns:1fr}.nursery-card.logs-card{grid-column:auto}.logs-card img{width:100px;height:82px}}`;document.head.appendChild(nurseryStyle);
renderCategories();

(function restoreRealPhotosAndSimpleLayout(){
  const real={maintenance:'https://www.gardeningknowhow.com/wp-content/uploads/2020/12/gardener-pruning.jpg',seasonal:'https://der-kleine-horror-garten.de/wp-content/uploads/2017/11/Garten-winterfest-machen-3-1.jpg',hedge:'https://aimbestmowing.com/_next/image?q=75&url=%2Fhedge-trimming-wide.png&w=3840',office:'https://www.leicester.gov.uk/media/178298/happy_mowing.jpg',bulbs:'https://busybeegardencentre.co.uk/cdn/shop/files/20251119_122931.jpg?v=1763571603&width=1500',winter:'https://images.openai.com/static-rsc-4/MOBgdR8ntQzFN6t-HFuG25Mcx7irMYjEfGs7KenpXCIB431fn_-vq-W8rXkwSdpMw8tJqg5OwYZ44-GF_bvzFXiOxHSxhG4OGmlb9XS_AkvdtpptZQJ_uGGY2ZJyx2lKZx9_y49fElXyXVLPdKPIP_RPZdRmJlVbSw7n3wW0XJvX7OnZPySGsUYJu2GMMqEK?purpose=fullsize'};
  const setBg=(sel,url)=>document.querySelectorAll(sel).forEach(el=>{el.style.backgroundImage=`url("${url}")`;});
  setBg('.photo-maintenance',real.maintenance);setBg('.photo-tidy',real.seasonal);setBg('.photo-hedges',real.hedge);setBg('.photo-office',real.office);setBg('.photo-winter',real.winter);
  document.querySelectorAll('#nursery .nursery-category .photo-aquatics').forEach(el=>{el.style.backgroundImage=`url("${real.bulbs}")`;el.style.backgroundPosition='center';});
  const oldHedge=document.querySelector('#hedge-domestic');if(oldHedge)oldHedge.remove();
  const hedgeLink=document.querySelector('.service-card-link[href="#hedge-work"]');if(hedgeLink){hedgeLink.href='#mms-our-work';hedgeLink.style.pointerEvents='auto';}
  const oldWork=document.querySelector('#mms-our-work');if(oldWork)oldWork.remove();
  const work=document.createElement('section');work.id='mms-our-work';work.innerHTML=`<small>OUR WORK</small><h2>Real work. Real gardens.</h2><p class="intro">A few examples of the work MMS can provide across Nottingham.</p><div class="grid mms-job-grid"><article class="mms-job-card"><div class="service-photo" style="background-image:url('${real.maintenance}')"></div><h3>Garden Maintenance</h3><p>Regular lawn care and garden upkeep.</p></article><article class="mms-job-card"><div class="service-photo" style="background-image:url('${real.seasonal}')"></div><h3>Seasonal Tidy-Ups</h3><p>Autumn clearance and winter preparation.</p></article><article class="mms-job-card hedge-job-card" tabindex="0" role="button"><div class="service-photo" style="background-image:url('${real.hedge}')"></div><h3>Hedge Work</h3><p>One of our specialties.</p><div class="hedge-options"><button type="button" class="btn light" data-hedge="domestic">Domestic</button><button type="button" class="btn light" data-hedge="commercial">Commercial</button></div><div class="hedge-detail" id="hedge-domestic-detail" hidden><h4>Domestic Hedge Work</h4><p>Hedge trimming, shaping, reductions and tidy-ups for homes and gardens.</p><div class="hedge-gallery"><div class="service-photo" style="background-image:url('${real.hedge}')"></div></div></div><div class="hedge-detail" id="hedge-commercial-detail" hidden><h4>Commercial Hedge Work</h4><p>Professional hedge maintenance for commercial sites, grounds and larger properties.</p><div class="hedge-gallery"><div class="service-photo" style="background-image:url('${real.hedge}')"></div></div></div></article><article class="mms-job-card"><div class="service-photo" style="background-image:url('${real.office}')"></div><h3>Grounds Maintenance</h3><p>Practical care for larger outdoor spaces.</p></article></div>`;
  const reviews=document.querySelector('#reviews');if(reviews)reviews.parentNode.insertBefore(work,reviews);
  work.querySelectorAll('[data-hedge]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();work.querySelectorAll('.hedge-detail').forEach(d=>d.hidden=true);work.querySelector(`#hedge-${btn.dataset.hedge}-detail`).hidden=false;}));
  const s=document.createElement('style');s.textContent='.mms-job-grid{grid-template-columns:repeat(4,1fr)}.hedge-job-card{cursor:default}.hedge-options{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.hedge-options .btn{margin:0}.hedge-detail{margin-top:18px;padding-top:16px;border-top:1px solid rgba(0,0,0,.12)}.hedge-detail h4{margin:0 0 8px}.hedge-gallery .service-photo{min-height:180px;border-radius:14px}@media(max-width:900px){.mms-job-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.mms-job-grid{grid-template-columns:1fr}}';document.head.appendChild(s);
})();

(function addAquaticsGallery(){
  const aquaticsCard=[...document.querySelectorAll('#services article')].find(card=>card.querySelector('h3')?.textContent.trim()==='Aquatics & Water Features');
  if(!aquaticsCard)return;
  aquaticsCard.classList.add('clickable-real-work');aquaticsCard.setAttribute('role','button');aquaticsCard.setAttribute('tabindex','0');
  const gallery=document.createElement('section');gallery.id='aquatics-gallery';gallery.innerHTML=`<small>AQUATICS & WATER FEATURES</small><h2>Aquatics — Our Work</h2><p class="intro">Real MMS aquatics and water-feature photographs. Click the main service above to see the full selection of our work.</p><div class="grid aquatics-gallery-grid"><article><img class="real-work-photo" src="images/aquatics-1.jpg" alt="MMS aquatics and water features photograph 1"></article><article><img class="real-work-photo" src="images/aquatics-2.jpg" alt="MMS aquatics and water features photograph 2"></article><article><img class="real-work-photo" src="images/aquatics-3.jpg" alt="MMS aquatics and water features photograph 3"></article><article><img class="real-work-photo" src="images/aquatics-4.jpg" alt="MMS aquatics and water features photograph 4"></article></div><a class="btn" href="#contact" data-quote="aquatics">Request an aquatics quote</a>`;
  const commercial=document.querySelector('#commercial');if(commercial)commercial.parentNode.insertBefore(gallery,commercial);else document.querySelector('main')?.appendChild(gallery);
  const go=()=>gallery.scrollIntoView({behavior:'smooth',block:'start'});aquaticsCard.addEventListener('click',go);aquaticsCard.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}});
  const style=document.createElement('style');style.textContent=`#services .clickable-real-work{cursor:pointer;transition:transform .18s ease,box-shadow .18s ease}#services .clickable-real-work:hover,#services .clickable-real-work:focus{transform:translateY(-3px);box-shadow:0 12px 30px rgba(24,48,39,.14);outline:2px solid #245b3a;outline-offset:2px}.aquatics-gallery-grid{grid-template-columns:repeat(2,1fr)}#aquatics-gallery{background:#f6f4ed}@media(max-width:520px){.aquatics-gallery-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  document.querySelectorAll('[data-quote]').forEach(a=>a.addEventListener('click',()=>{if(typeof qt!=='undefined'&&qt&&a.dataset.quote==='aquatics'){qt.value='💧 AQUATICS / POND QUOTE';if(typeof es!=='undefined'&&es)es.value=qt.value+' — MMS Gardening Services';}}));
})();

// Garden Maintenance: make the main service card open the dedicated maintenance work gallery.
(function addGardenMaintenanceGalleryLink(){
  const card=[...document.querySelectorAll('#services article')].find(el=>el.querySelector('h3')?.textContent.trim()==='Garden Maintenance');
  if(!card)return;
  card.classList.add('clickable-real-work');card.setAttribute('role','link');card.setAttribute('tabindex','0');
  const go=()=>{window.location.href='garden-maintenance.html';};
  card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}});
})();